from typing import Optional
from .. import auth as auth, utils as utils

class PluginApiMixin:
    def configure_plugin(self, name: str, options: dict[str, str]) -> None: ...
    def create_plugin(
        self, name: str, plugin_data_dir: str, gzip: bool = False
    ) -> None: ...
    def disable_plugin(self, name: str, force: bool = False) -> None: ...
    def enable_plugin(self, name: str, timeout: int = 30) -> None: ...
    def inspect_plugin(self, name: str) -> dict[str, str]: ...
    def pull_plugin(
        self, remote: str, privileges: list[str], name: Optional[str] = None
    ) -> None: ...
    def plugins(self) -> list[dict[str, str]]: ...
    def plugin_privileges(self, name: str) -> list[str]: ...
    def push_plugin(self, name: str) -> None: ...
    def remove_plugin(self, name: str, force: bool = False) -> None: ...
    def upgrade_plugin(self, name: str, remote: str, privileges: list[str]) -> None: ...
