from .. import errors as errors, utils as utils
from _typeshed import Incomplete

class VolumeApiMixin:
    def volumes(self, filters: Incomplete | None = ...): ...
    def create_volume(self, name: Incomplete | None = ..., driver: Incomplete | None = ..., driver_opts: Incomplete | None = ..., labels: Incomplete | None = ...): ...
    def inspect_volume(self, name): ...
    def prune_volumes(self, filters: Incomplete | None = ...): ...
    def remove_volume(self, name, force: bool = ...) -> None: ...
