from _typeshed import Incomplete
from docker import utils as utils
from docker.constants import (
    DEFAULT_UNIX_SOCKET as DEFAULT_UNIX_SOCKET,
    IS_WINDOWS_PLATFORM as IS_WINDOWS_PLATFORM,
)
from docker.utils.config import find_config_file as find_config_file

METAFILE: str

def get_current_context_name() -> str: ...
def write_context_name_to_docker_config(name: str | None = ...): ...
def get_context_id(name: str) -> str: ...
def get_context_dir() -> str: ...
def get_meta_dir(name: str | None = ...) -> str: ...
def get_meta_file(name: str) -> str: ...
def get_tls_dir(name: str | None = ..., endpoint: str = ...) -> str: ...
def get_context_host(path: str | None = ..., tls: bool = ...) -> str: ...
