from typing import Optional, Union
from ..constants import IS_WINDOWS_PLATFORM
from .fnmatch import fnmatch
from io import BytesIO

def tar(
    path: str,
    exclude: Optional[list[str]] = None,
    dockerfile: Optional[str] = None,
    fileobj: Optional[BytesIO] = None,
    gzip: bool = False,
) -> BytesIO: ...
def exclude_paths(
    root: str, patterns: list[str], dockerfile: Optional[str] = None
) -> list[str]: ...
def build_file_list(root: str) -> list[str]: ...
def create_archive(
    root: str,
    files: Optional[list[str]] = None,
    fileobj: Optional[BytesIO] = None,
    gzip: bool = False,
    extra_files: Optional[list[tuple[str, str]]] = None,
) -> BytesIO: ...
def mkbuildcontext(dockerfile: str) -> BytesIO: ...
def split_path(p: str) -> list[str]: ...
def normalize_slashes(p: str) -> str: ...
def walk(root: str, patterns: list[str], default: bool = True) -> list[str]: ...

class PatternMatcher:
    patterns: list[str]
    def __init__(self, patterns: list[str]) -> None: ...
    def matches(self, filepath: str) -> bool: ...
    def walk(self, root: str) -> list[str]: ...

class Pattern:
    exclusion: bool
    dirs: list[str]
    cleaned_pattern: str
    def __init__(self, pattern_str: str) -> None: ...
    @classmethod
    def normalize(cls, p: str) -> str: ...
    def match(self, filepath: str) -> bool: ...
