from ..constants import IS_WINDOWS_PLATFORM as IS_WINDOWS_PLATFORM
from .fnmatch import fnmatch as fnmatch
from _typeshed import Incomplete

def match_tag(tag: str) -> bool: ...
def tar(
    path,
    exclude: Incomplete | None = ...,
    dockerfile: Incomplete | None = ...,
    fileobj: Incomplete | None = ...,
    gzip: bool = ...,
): ...
def exclude_paths(root, patterns, dockerfile: Incomplete | None = ...): ...
def build_file_list(root): ...
def create_archive(
    root,
    files: Incomplete | None = ...,
    fileobj: Incomplete | None = ...,
    gzip: bool = ...,
    extra_files: Incomplete | None = ...,
): ...
def mkbuildcontext(dockerfile): ...
def split_path(p): ...
def normalize_slashes(p): ...
def walk(root, patterns, default: bool = ...): ...

class PatternMatcher:
    patterns: Incomplete
    def __init__(self, patterns) -> None: ...
    def matches(self, filepath): ...
    def walk(self, root): ...

class Pattern:
    exclusion: bool
    dirs: Incomplete
    cleaned_pattern: Incomplete
    def __init__(self, pattern_str) -> None: ...
    @classmethod
    def normalize(cls, p): ...
    def match(self, filepath): ...
