from typing import Optional, Dict, Any
from ..constants import IS_WINDOWS_PLATFORM

DOCKER_CONFIG_FILENAME: str
LEGACY_DOCKER_CONFIG_FILENAME: str

def find_config_file(config_path: Optional[str] = None) -> str: ...
def config_path_from_environment() -> str: ...
def home_dir() -> str: ...
def load_general_config(config_path: Optional[str] = None) -> Dict[str, Any]: ...
