from typing import Callable, Any
from . import utils as utils
from .. import errors as errors

def check_resource(resource_name: str) -> Callable[..., Any]: ...
def minimum_version(version: str) -> Callable[..., Any]: ...
def update_headers(f: Callable[..., Any]) -> Callable[..., Any]: ...
