from typing import Generator, Optional, Any
from ..errors import StreamParseError
from json import JSONDecoder

json_decoder: JSONDecoder

def stream_as_text(stream: Any) -> Generator[str, None, None]: ...
def json_splitter(buffer: str) -> Generator[str, None, None]: ...
def json_stream(stream: Any) -> Generator[Any, None, None]: ...
def line_splitter(buffer: str, separator: str = "\n") -> Generator[str, None, None]: ...
def split_buffer(
    stream: Any,
    splitter: Optional[Generator[str, None, None]] = None,
    decoder: Optional[JSONDecoder] = None,
) -> Generator[str, None, None]: ...
