from typing import Optional
from .utils import format_environment as format_environment

class ProxyConfig(dict):
    @property
    def http(self) -> Optional[str]: ...
    @property
    def https(self) -> Optional[str]: ...
    @property
    def ftp(self) -> Optional[str]: ...
    @property
    def no_proxy(self) -> Optional[str]: ...
    @staticmethod
    def from_dict(config: dict) -> "ProxyConfig": ...
    def get_environment(self) -> dict: ...
    def inject_proxy_environment(self, environment: dict) -> None: ...
