from .utils import format_environment as format_environment

class ProxyConfig(dict):
    @property
    def http(self): ...
    @property
    def https(self): ...
    @property
    def ftp(self): ...
    @property
    def no_proxy(self): ...
    @staticmethod
    def from_dict(config): ...
    def get_environment(self): ...
    def inject_proxy_environment(self, environment): ...
