from typing import Dict, Optional, Any
from .utils import format_environment as format_environment

class ProxyConfig(Dict[str, Any]):
    @property
    def http(self) -> Optional[str]: ...
    @property
    def https(self) -> Optional[str]: ...
    @property
    def ftp(self) -> Optional[str]: ...
    @property
    def no_proxy(self) -> Optional[str]: ...
    @staticmethod
    def from_dict(config: Dict[str, Any]) -> "ProxyConfig": ...
    def get_environment(self) -> Dict[str, Any]: ...
    def inject_proxy_environment(self, environment: Dict[str, Any]) -> None: ...
