from typing import Optional, Any
from . import credentials as credentials, errors as errors
from .utils import config as config
from logging import Logger

INDEX_NAME: str
INDEX_URL: str
TOKEN_USERNAME: str
log: Logger

def resolve_repository_name(repo_name: str) -> str: ...
def resolve_index_name(index_name: str) -> str: ...
def get_config_header(client: Any, registry: str) -> dict[str, str]: ...
def split_repo_name(repo_name: str) -> tuple[str, str]: ...
def get_credential_store(authconfig: dict[str, Any], registry: str) -> Any: ...

class AuthConfig(dict):
    def __init__(
        self, dct: dict[str, Any], credstore_env: Optional[dict[str, Any]] = None
    ) -> None: ...
    @classmethod
    def parse_auth(
        cls, entries: dict[str, Any], raise_on_error: bool = False
    ) -> dict[str, Any]: ...
    @classmethod
    def load_config(
        cls,
        config_path: str,
        config_dict: dict[str, Any],
        credstore_env: Optional[dict[str, Any]] = None,
    ) -> "AuthConfig": ...
    @property
    def auths(self) -> dict[str, Any]: ...
    @property
    def creds_store(self) -> str: ...
    @property
    def cred_helpers(self) -> dict[str, Any]: ...
    @property
    def is_empty(self) -> bool: ...
    def resolve_authconfig(self, registry: Optional[str] = None) -> dict[str, Any]: ...
    def get_credential_store(self, registry: str) -> Any: ...
    def get_all_credentials(self) -> dict[str, Any]: ...
    def add_auth(self, reg: str, data: dict[str, Any]) -> None: ...

def resolve_authconfig(
    authconfig: dict[str, Any],
    registry: Optional[str] = None,
    credstore_env: Optional[dict[str, Any]] = None,
) -> dict[str, Any]: ...
def convert_to_hostname(url: str) -> str: ...
def decode_auth(auth: str) -> dict[str, Any]: ...
def encode_header(auth: dict[str, Any]) -> str: ...
def parse_auth(
    entries: dict[str, Any], raise_on_error: bool = False
) -> dict[str, Any]: ...
def load_config(
    config_path: Optional[str] = None,
    config_dict: Optional[dict[str, Any]] = None,
    credstore_env: Optional[dict[str, Any]] = None,
) -> dict[str, Any]: ...
