from _typeshed import Incomplete

DEFAULT_DOCKER_API_VERSION: str
MINIMUM_DOCKER_API_VERSION: str
DEFAULT_TIMEOUT_SECONDS: int
STREAM_HEADER_SIZE_BYTES: int
CONTAINER_LIMITS_KEYS: Incomplete
DEFAULT_HTTP_HOST: str
DEFAULT_UNIX_SOCKET: str
DEFAULT_NPIPE: str
BYTE_UNITS: Incomplete
INSECURE_REGISTRY_DEPRECATION_WARNING: str
IS_WINDOWS_PLATFORM: Incomplete
WINDOWS_LONGPATH_PREFIX: str
DEFAULT_USER_AGENT: Incomplete
DEFAULT_NUM_POOLS: int
DEFAULT_NUM_POOLS_SSH: int
DEFAULT_MAX_POOL_SIZE: int
DEFAULT_DATA_CHUNK_SIZE: Incomplete
DEFAULT_SWARM_ADDR_POOL: Incomplete
DEFAULT_SWARM_SUBNET_SIZE: int
