from typing import Any, Dict, Optional, List
from ..api import APIClient as APIClient
from .resource import Collection as Collection, Model as Model

class Config(Model):
    id_attribute: str = "ID"
    @property
    def name(self) -> str: ...
    def remove(self) -> None: ...

class ConfigCollection(Collection):
    model = Config
    def create(self, **kwargs: Any) -> Config: ...
    def get(self, config_id: str) -> Config: ...
    def list(self, **kwargs: Any) -> List[Config]: ...
