from ..api import APIClient as APIClient
from .resource import Collection as Collection, Model as Model

class Config(Model):
    id_attribute: str
    @property
    def name(self) -> str: ...
    def remove(self) -> None: ...

class ConfigCollection(Collection):
    model = Config
    def create(self, **kwargs) -> Config: ...
    def get(self, config_id) -> Config: ...
    def list(self, **kwargs) -> list[Config]: ...
