from .resource import Collection as Collection, Model as Model
from ..types.misc_types import TrueOnSuccess


class Node(Model):
    id_attribute: str
    @property
    def version(self) -> str: ...
    def update(self, node_spec: dict) -> TrueOnSuccess: ...
    def remove(self, force: bool = ...) -> TrueOnSuccess: ...

class NodeCollection(Collection):
    model = Node
    def get(self, node_id: str) -> Node: ...
    def list(self, *args, **kwargs) -> list[Node]: ...
