from ..api import APIClient as APIClient
from .resource import Collection as Collection, Model as Model

class Secret(Model):
    id_attribute: str
    @property
    def name(self) -> str: ...
    def remove(self) -> None: ...

class SecretCollection(Collection):
    model = Secret
    def create(self, **kwargs) -> Model: ...
    def get(self, secret_id: str) -> Secret: ...
    def list(self, **kwargs) -> list[Secret]: ...
