from typing import Any
from ..api import APIClient as APIClient
from .resource import Collection as Collection, Model as Model

class Secret(Model):
    id_attribute: str = "ID"
    @property
    def name(self) -> str: ...
    def remove(self) -> None: ...

class SecretCollection(Collection):
    model = Secret
    def create(self, **kwargs: Any) -> Secret: ...
    def get(self, secret_id: str) -> Secret: ...
    def list(self, **kwargs: Any) -> list[Secret]: ...
