from .resource import Collection as Collection, Model as Model
from _typeshed import Incomplete
from docker.errors import InvalidArgument as InvalidArgument, create_unexpected_kwargs_error as create_unexpected_kwargs_error
from docker.types import ContainerSpec as ContainerSpec, Placement as Placement, ServiceMode as ServiceMode, TaskTemplate as TaskTemplate

class Service(Model):
    id_attribute: str
    @property
    def name(self): ...
    @property
    def version(self): ...
    def remove(self): ...
    def tasks(self, filters: Incomplete | None = ...): ...
    def update(self, **kwargs): ...
    def logs(self, **kwargs): ...
    def scale(self, replicas): ...
    def force_update(self): ...

class ServiceCollection(Collection):
    model = Service
    def create(self, image, command: Incomplete | None = ..., **kwargs): ...
    def get(self, service_id, insert_defaults: Incomplete | None = ...): ...
    def list(self, **kwargs): ...

CONTAINER_SPEC_KWARGS: Incomplete
TASK_TEMPLATE_KWARGS: Incomplete
CREATE_SERVICE_KWARGS: Incomplete
PLACEMENT_KWARGS: Incomplete
