from ..api import APIClient as APIClient
from .resource import Collection as Collection, Model as Model
from typing import Optional, Dict, Any, List

class Volume(Model):
    id_attribute: str = "Name"
    @property
    def name(self) -> str: ...
    def remove(self, force: bool = False) -> None: ...

class VolumeCollection(Collection):
    model = Volume
    def create(
        self, name: Optional[str] = None, **kwargs: Dict[str, Any]
    ) -> Volume: ...
    def get(self, volume_id: str) -> Volume: ...
    def list(self, **kwargs: Dict[str, Any]) -> List[Volume]: ...
    def prune(self, filters: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
