from . import constants as constants, errors as errors
from .utils import create_environment_dict as create_environment_dict
from _typeshed import Incomplete

class Store:
    program: Incomplete
    exe: Incomplete
    environment: Incomplete
    def __init__(self, program, environment: Incomplete | None = ...) -> None: ...
    def get(self, server): ...
    def store(self, server, username, secret): ...
    def erase(self, server) -> None: ...
    def list(self): ...
