from typing import Any, Optional
from . import constants as constants, errors as errors
from .utils import create_environment_dict as create_environment_dict

class Store:
    program: str
    exe: str
    environment: dict[str, Any]
    def __init__(
        self, program: str, environment: Optional[dict[str, Any]] = None
    ) -> None: ...
    def get(self, server: str) -> dict[str, Any]: ...
    def store(self, server: str, username: str, secret: str) -> None: ...
    def erase(self, server: str) -> None: ...
    def list(self) -> list[dict[str, Any]]: ...
