from typing import Any, Iterator

class CancellableStream:
    def __init__(self, stream: Any, response: Any) -> None: ...
    def __iter__(self) -> Iterator: ...
    def __next__(self) -> Any: ...
    next = __next__
    def close(self) -> None: ...
