from .base import DictType as DictType

class Healthcheck(DictType):
    def __init__(self, **kwargs) -> None: ...
    @property
    def test(self): ...
    @property
    def interval(self): ...
    @property
    def timeout(self): ...
    @property
    def retries(self): ...
    @property
    def start_period(self): ...
